---
- name: Warn if no user specified
  debug: msg="No user specified with the user var, this may cause issues in other rolesâ€¦"
  when: user is not defined

- name: Check for user
  command:
    getent passwd {{ user }}
  ignore_errors: yes
  changed_when: no
  register: passwd

- name: Fail if user does not exist
  fail: msg="User supplied as user does not exist."
  when: passwd|failed
